# Generated by Django 6.0.5 on 2026-05-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winklestoreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField()),
                ('profile_picture', models.ImageField(upload_to='profile_picture/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
