# Generated by Django 6.0.5 on 2026-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winklestoreapp', '0002_buyeruser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeruser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
