# Generated by Django 6.0.5 on 2026-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winklestoreapp', '0003_alter_buyeruser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
