# Generated by Django 6.0.5 on 2026-05-19 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winklestoreapp', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winklestoreapp.buyeruser'),
        ),
    ]
