# Generated by Django 6.0.5 on 2026-05-19 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winklestoreapp', '0006_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winklestoreapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winklestoreapp.buyeruser')),
            ],
        ),
    ]
